#!/usr/bin/env python3
"""
Build and push a Hugging Face dataset from a folder of ground-annotate scenes.

Each scene subdirectory is expected to look like:
  <root>/<scene_id>/
    - image_a.<ext>
    - image_b.<ext>
    - annotation.json        # produced by the annotation tool and mask script
    - mask_b.png             # produced by generate_mask.py

The annotation.json format (after mask generation) is:
{
  "scene": "scene_001",
  "annotation": {
    "point": {"x": 512.4, "y": 318.2},
    "label": "bicycle",
    "updated_at": "2024-05-01T12:34:56.789123+00:00",
    "image": "image_b.jpg",
    "image_size": {"width": 1024, "height": 768},
    "mask": "mask_b.png"
  }
}

This script mirrors the style of `data_push_ADE20K_distraction.py`:
- collect all samples
- define a `Features` schema with `datasets.Image` columns
- create a DatasetDict and push it to the Hub.

Only essential fields are pushed:
- id
- image_a
- image_b
- mask_b
- label
- point_b (annotation point normalized to [0, 1] in image_b coordinates)
"""

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple, Any

from datasets import Dataset, DatasetDict, Features, Image, Sequence, Value
from PIL import Image as PILImage


def find_image(path: Path, stem: str) -> Path:
    """
    Find an image file in `path` with base name `stem` and common image extensions.
    First tries exact lowercase naming (e.g. image_a.jpg), then case-insensitive
    basename matching (e.g. Image_A.JPG).
    """
    exts = [".jpg", ".jpeg", ".png", ".bmp", ".webp"]

    # Exact conventional name first.
    for ext in exts:
        candidate = path / f"{stem}{ext}"
        if candidate.exists():
            return candidate

    # Case-insensitive basename fallback.
    target = stem.lower()
    for entry in sorted(path.iterdir()):
        if not entry.is_file():
            continue
        if entry.suffix.lower() not in exts:
            continue
        if entry.stem.lower() == target:
            return entry

    raise FileNotFoundError(f"No image found for '{stem}' under {path}")


def load_scene(scene_dir: Path) -> Dict[str, Any]:
    """
    Load a single scene directory into a dict compatible with Hugging Face datasets.
    """
    annotation_path = scene_dir / "annotation.json"
    if not annotation_path.exists():
        raise FileNotFoundError(f"Missing annotation.json in {scene_dir}")

    with annotation_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    scene_id = str(data.get("scene", scene_dir.name))
    ann = data.get("annotation", {}) or {}

    point = ann.get("annotation_point") or ann.get("point", {}) or {}

    # Images and mask paths (HF datasets.Image accepts local file paths)
    image_a_path = find_image(scene_dir, "image_a")
    image_b_path = find_image(scene_dir, "image_b")
    # mask_b is generated by generate_mask.py; fall back to mask.png if needed
    mask_name = ann.get("mask") or "mask_b.png"
    mask_path = scene_dir / mask_name
    if not mask_path.exists():
        # backward compatibility: some setups may use `mask.png`
        alt = scene_dir / "mask.png"
        if alt.exists():
            mask_path = alt
        else:
            raise FileNotFoundError(f"Mask file not found in {scene_dir} (expected {mask_name} or mask.png)")

    if "x" not in point or "y" not in point:
        raise ValueError(f"Missing annotation point in {scene_dir / 'annotation.json'}")

    with PILImage.open(image_b_path) as img_b:
        image_b_width, image_b_height = img_b.size
    if image_b_width <= 0 or image_b_height <= 0:
        raise ValueError(f"Invalid image_b size in {scene_dir}: {(image_b_width, image_b_height)}")

    point_x_norm = min(1.0, max(0.0, float(point["x"]) / float(image_b_width)))
    point_y_norm = min(1.0, max(0.0, float(point["y"]) / float(image_b_height)))

    sample = {
        "id": scene_id,
        "image_a": str(image_a_path),
        "image_b": str(image_b_path),
        "mask_b": str(mask_path),
        "label": ann.get("label", ""),
        "point_b": [point_x_norm, point_y_norm],
    }

    return sample


def collect_scenes(root: Path) -> List[Path]:
    """
    Collect all scene subdirectories (those containing annotation.json).
    """
    scenes: List[Path] = []
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        if (child / "annotation.json").exists():
            scenes.append(child)
    return scenes


def split_indices(n: int, val_ratio: float) -> Tuple[List[int], List[int]]:
    """
    Split indices [0, n) into train/validation with given ratio (by prefix).
    """
    if n == 0:
        return [], []
    val_count = int(round(n * val_ratio))
    val_indices = list(range(val_count))
    train_indices = list(range(val_count, n))
    return train_indices, val_indices


def build_dataset_dict(
    samples: List[Dict[str, Any]],
    split_mode: str,
    val_ratio: float,
) -> DatasetDict:
    """
    Build a DatasetDict with typed features.

    split_mode:
      - "test": all samples are placed in a single test split (default)
      - "train_val": split into train/validation by prefix and val_ratio
    """
    # Define features explicitly so that image columns are treated as images.
    features = Features(
        {
            "id": Value("string"),
            "image_a": Image(),
            "image_b": Image(),
            "mask_b": Image(),
            "label": Value("string"),
            # Store point as [x, y] normalized to [0, 1] in image_b coordinates.
            "point_b": Sequence(Value("float32"), length=2),
        }
    )

    if split_mode == "test":
        ds_test = Dataset.from_list(samples).cast(features)
        return DatasetDict({"test": ds_test})

    n = len(samples)
    train_idx, val_idx = split_indices(n, val_ratio)
    train_samples = [samples[i] for i in train_idx]
    val_samples = [samples[i] for i in val_idx]

    ds_train = Dataset.from_list(train_samples).cast(features)
    ds_dict: Dict[str, Dataset] = {"train": ds_train}
    if val_samples:
        ds_val = Dataset.from_list(val_samples).cast(features)
        ds_dict["validation"] = ds_val
    return DatasetDict(ds_dict)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Push a ground-annotate dataset (scenes with image_a, image_b, mask_b) to the Hugging Face Hub.",
    )
    parser.add_argument(
        "data_root",
        type=str,
        help="Path to root folder containing scene subdirectories (e.g., example_data).",
    )
    parser.add_argument(
        "--repo-id",
        type=str,
        required=True,
        help="Target Hugging Face Hub dataset repo id, e.g. 'username/ground-annotate'.",
    )
    parser.add_argument(
        "--split-mode",
        type=str,
        choices=["test", "train_val"],
        default="test",
        help="Dataset split mode: 'test' (default, all data in test split) or 'train_val'.",
    )
    parser.add_argument(
        "--val-ratio",
        type=float,
        default=0.1,
        help="Fraction of samples to reserve for validation when --split-mode train_val (default: 0.1).",
    )
    parser.add_argument(
        "--private",
        action="store_true",
        help="Create/push the dataset as a private repo on the Hub.",
    )

    args = parser.parse_args()

    data_root = Path(args.data_root).expanduser().resolve()
    if not data_root.is_dir():
        raise SystemExit(f"Data root '{data_root}' does not exist or is not a directory.")

    print(f"Collecting scenes from: {data_root}")
    scenes = collect_scenes(data_root)
    if not scenes:
        raise SystemExit(f"No scene directories with annotation.json found under {data_root}")

    print(f"Found {len(scenes)} annotated scene(s).")

    samples: List[Dict[str, Any]] = []
    for scene_dir in scenes:
        try:
            sample = load_scene(scene_dir)
            samples.append(sample)
        except Exception as e:
            print(f"Skipping scene {scene_dir.name} due to error: {e}")

    if not samples:
        raise SystemExit("No valid samples were loaded; aborting.")

    print(f"Loaded {len(samples)} sample(s); building DatasetDict (split_mode={args.split_mode})...")
    ds = build_dataset_dict(samples, split_mode=args.split_mode, val_ratio=args.val_ratio)

    print(ds)
    first_split = next(iter(ds.keys()))
    print(ds[first_split][0])

    print(f"Pushing to Hub: {args.repo_id} (private={args.private})")
    ds.push_to_hub(args.repo_id, private=bool(args.private))

    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


