#!/usr/bin/env python3
"""
Build and push a Hugging Face dataset from a folder of ground-annotate scenes.

Each scene subdirectory is expected to look like:
  <root>/<scene_id>/
    - image_a.<ext>
    - image_b.<ext>
    - annotation.json        # produced by the annotation tool and mask script
    - mask_b.png             # produced by generate_mask.py

The annotation.json format (after mask generation) is:
{
  "scene": "scene_001",
  "annotation": {
    "point": {"x": 512.4, "y": 318.2},
    "label": "bicycle",
    "updated_at": "2024-05-01T12:34:56.789123+00:00",
    "image": "image_b.jpg",
    "image_size": {"width": 1024, "height": 768},
    "mask": "mask_b.png"
  }
}

This script mirrors the style of `data_push_ADE20K_distraction.py`:
- collect all samples
- define a `Features` schema with `datasets.Image` columns
- create a DatasetDict and push it to the Hub.
"""

import argparse
import json
import os
from pathlib import Path
from typing import Dict, List, Tuple, Any

from datasets import Dataset, DatasetDict, Features, Image, Sequence, Value


def find_image(path: Path, stem: str) -> Path:
    """
    Find an image file in `path` with base name `stem` and common image extensions.
    """
    exts = [".jpg", ".jpeg", ".png", ".bmp", ".webp"]
    for ext in exts:
        candidate = path / f"{stem}{ext}"
        if candidate.exists():
            return candidate
    raise FileNotFoundError(f"No image found for '{stem}' under {path}")


def load_scene(scene_dir: Path) -> Dict[str, Any]:
    """
    Load a single scene directory into a dict compatible with Hugging Face datasets.
    """
    annotation_path = scene_dir / "annotation.json"
    if not annotation_path.exists():
        raise FileNotFoundError(f"Missing annotation.json in {scene_dir}")

    with annotation_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    scene_id = str(data.get("scene", scene_dir.name))
    ann = data.get("annotation", {}) or {}

    point = ann.get("point", {}) or {}
    image_size = ann.get("image_size", {}) or {}

    # Images and mask paths (HF datasets.Image accepts local file paths)
    image_a_path = find_image(scene_dir, "image_a")
    image_b_path = find_image(scene_dir, "image_b")
    # mask_b is generated by generate_mask.py; fall back to mask.png if needed
    mask_name = ann.get("mask") or "mask_b.png"
    mask_path = scene_dir / mask_name
    if not mask_path.exists():
        # backward compatibility: some setups may use `mask.png`
        alt = scene_dir / "mask.png"
        if alt.exists():
            mask_path = alt

    sample = {
        "id": scene_id,
        "scene": scene_id,
        "image_a": str(image_a_path),
        "image_b": str(image_b_path),
        "mask_b": str(mask_path),
        "label": ann.get("label", ""),
        "updated_at": ann.get("updated_at", ""),
        "point": [
            [float(point["x"])] if "x" in point else [],
            [float(point["y"])] if "y" in point else [],
        ],
        "image_width": int(image_size["width"]) if "width" in image_size else -1,
        "image_height": int(image_size["height"]) if "height" in image_size else -1,
    }

    return sample


def collect_scenes(root: Path) -> List[Path]:
    """
    Collect all scene subdirectories (those containing annotation.json).
    """
    scenes: List[Path] = []
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        if (child / "annotation.json").exists():
            scenes.append(child)
    return scenes


def split_indices(n: int, val_ratio: float) -> Tuple[List[int], List[int]]:
    """
    Split indices [0, n) into train/validation with given ratio (by prefix).
    """
    if n == 0:
        return [], []
    val_count = int(round(n * val_ratio))
    val_indices = list(range(val_count))
    train_indices = list(range(val_count, n))
    return train_indices, val_indices


def build_dataset_dict(
    samples: List[Dict[str, Any]],
    val_ratio: float,
) -> DatasetDict:
    """
    Build a DatasetDict with train/validation splits and typed features.
    """
    # Define features explicitly so that image columns are treated as images.
    features = Features(
        {
            "id": Value("string"),
            "scene": Value("string"),
            "image_a": Image(),
            "image_b": Image(),
            "mask_b": Image(),
            "label": Value("string"),
            "updated_at": Value("string"),
            # Store point as 2x1 nested sequence [[x], [y]]
            "point": Sequence(Sequence(Value("float32"))),
            "image_width": Value("int32"),
            "image_height": Value("int32"),
        }
    )

    n = len(samples)
    train_idx, val_idx = split_indices(n, val_ratio)

    # Simple prefix-based split
    train_samples = [samples[i] for i in train_idx]
    val_samples = [samples[i] for i in val_idx]

    ds_train = Dataset.from_list(train_samples).cast(features)
    ds_dict: Dict[str, Dataset] = {"train": ds_train}

    if val_samples:
        ds_val = Dataset.from_list(val_samples).cast(features)
        ds_dict["validation"] = ds_val

    return DatasetDict(ds_dict)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Push a ground-annotate dataset (scenes with image_a, image_b, mask_b) to the Hugging Face Hub.",
    )
    parser.add_argument(
        "data_root",
        type=str,
        help="Path to root folder containing scene subdirectories (e.g., example_data).",
    )
    parser.add_argument(
        "--repo-id",
        type=str,
        required=True,
        help="Target Hugging Face Hub dataset repo id, e.g. 'username/ground-annotate'.",
    )
    parser.add_argument(
        "--val-ratio",
        type=float,
        default=0.1,
        help="Fraction of samples to reserve for validation (default: 0.1).",
    )
    parser.add_argument(
        "--private",
        action="store_true",
        help="Create/push the dataset as a private repo on the Hub.",
    )

    args = parser.parse_args()

    data_root = Path(args.data_root).expanduser().resolve()
    if not data_root.is_dir():
        raise SystemExit(f"Data root '{data_root}' does not exist or is not a directory.")

    print(f"Collecting scenes from: {data_root}")
    scenes = collect_scenes(data_root)
    if not scenes:
        raise SystemExit(f"No scene directories with annotation.json found under {data_root}")

    print(f"Found {len(scenes)} annotated scene(s).")

    samples: List[Dict[str, Any]] = []
    for scene_dir in scenes:
        try:
            sample = load_scene(scene_dir)
            samples.append(sample)
        except Exception as e:
            print(f"Skipping scene {scene_dir.name} due to error: {e}")

    if not samples:
        raise SystemExit("No valid samples were loaded; aborting.")

    print(f"Loaded {len(samples)} sample(s); building DatasetDict...")
    ds = build_dataset_dict(samples, val_ratio=args.val_ratio)

    print(ds)
    print(ds["train"][0])

    print(f"Pushing to Hub: {args.repo_id} (private={args.private})")
    ds.push_to_hub(args.repo_id, private=bool(args.private))

    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


